- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no

  # e.g.
  # - package_name
  # or
  # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
  #
  # state choices: [head, latest, present, absent, linked, unlinked] (default latest)
  # install_options: string or sequence (default none)
  vars:
    homebrew_taps:
      - caskroom/cask
      - homebrew/php
      - homebrew/apache
      - homebrew/completions
    homebrew_packages:
      - { name: readline }
      - { name: openssl, state: linked, install_options: force }
      
      - { name: python }
      - { name: ansible }
      
      - { name: git }
      - { name: hub }
      - { name: tig }
      
      - { name: wget }
      - { name: curl }
      - { name: tree }
      - { name: jq }
      - { name: rmtrash }
      
      - { name: go }
      - { name: peco }
      - { name: ghq }
      
      - { name: mysql }
      - { name: sqlite }
      
      - { name: bash-completion }
      - { name: vagrant-completion }
      - { name: source-highlight}
      - { name: colordiff }
      
      - { name: httpd24 }
      
      - { name: node }
      
      - { name: php56 }
      - { name: php56-mcrypt }
      - { name: php56-intl }
      - { name: php56-opcache }
      - { name: php56-xdebug }
      - { name: php-cs-fixer }
      - { name: phpmd }
      - { name: composer }
      
      - { name: rbenv }
      - { name: ruby-build }
     
      - { name: bash }
      - { name: vim }
      - { name: zsh }
 
  tasks:
    
    - name: homebrew tap
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps
    
    - name: brew update
      homebrew: update_homebrew=yes
      ignore_errors: on
    
    - name: brew package install
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      ignore_errors: on
      
    - name: brew cleanup
      shell: $(brew --prefix)/bin/brew cleanup
      register: creanup_result
      changed_when: no
